import json
import logging
from io import BytesIO
from pathlib import Path
from typing import Any, Literal

from fastapi import APIRouter, Depends, HTTPException, Query, Request
from fastapi.responses import HTMLResponse, Response
from fastapi.templating import Jinja2Templates
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.api.deps import require_app_password, require_webhook_secret
from app.config import get_settings
from app.db import get_session
from app.models.report_run import ReportRun
from app.schemas.report import AttachReportRequest, ReportRunResponse
from app.services.analytics import report_context

logger = logging.getLogger(__name__)

router = APIRouter(tags=["report"], dependencies=[Depends(require_app_password)])
templates = Jinja2Templates(directory=str(Path(__file__).resolve().parents[1] / "templates"))
TEMPLATE_DIR = Path(__file__).resolve().parents[1] / "templates"
REPORT_CSS_PATH = TEMPLATE_DIR / "report.css"

CURRENCY_SYMBOLS: dict[str, str] = {"GBP": "\u00a3", "USD": "$", "EUR": "\u20ac"}
DEFAULT_CURRENCY = "GBP"
DEFAULT_HOURLY_RATE = 30.0
MIN_HOURLY_RATE = 10.0
MAX_HOURLY_RATE = 300.0


def _report_query_params(
    hourly_rate: float = Query(default=DEFAULT_HOURLY_RATE, ge=MIN_HOURLY_RATE, le=MAX_HOURLY_RATE),
    currency: Literal["GBP", "USD", "EUR"] = DEFAULT_CURRENCY,
) -> tuple[float, Literal["GBP", "USD", "EUR"]]:
    return hourly_rate, currency


@router.get("/report", response_class=HTMLResponse)
@router.get("/report.html", response_class=HTMLResponse)
def get_report(
    request: Request,
    params: tuple[float, Literal["GBP", "USD", "EUR"]] = Depends(_report_query_params),
    session: Session = Depends(get_session),
) -> HTMLResponse:
    hourly_rate, currency = params
    context = _build_report_view_model(
        report_context(session),
        hourly_rate=hourly_rate,
        currency=currency,
        quick_win_threshold=get_settings().report_quickwin_impact_threshold_hours,
    )
    return templates.TemplateResponse(name="report.html", context={"request": request, **context})


@router.get("/report.pdf")
def get_report_pdf(
    params: tuple[float, Literal["GBP", "USD", "EUR"]] = Depends(_report_query_params),
    session: Session = Depends(get_session),
) -> Response:
    hourly_rate, currency = params
    context = _build_report_view_model(
        report_context(session),
        hourly_rate=hourly_rate,
        currency=currency,
        quick_win_threshold=get_settings().report_quickwin_impact_threshold_hours,
    )
    html = templates.get_template("report.html").render(**context)

    try:
        from weasyprint import HTML  # type: ignore

        logger.info("PDF engine status: weasyprint available")
        pdf = HTML(string=html, base_url=str(TEMPLATE_DIR)).write_pdf()
    except Exception:
        logger.exception("PDF engine status: weasyprint unavailable or failed; attempting reportlab fallback")
        try:
            pdf = _build_reportlab_pdf(context)
        except Exception as fallback_exc:
            logger.exception("PDF engine status: reportlab fallback failed")
            raise HTTPException(
                status_code=500,
                detail="PDF export is currently unavailable. HTML report remains available at /report.html.",
            ) from fallback_exc

    headers = {"Content-Disposition": "attachment; filename=friction-finder-report.pdf"}
    return Response(content=pdf, media_type="application/pdf", headers=headers)


def _build_reportlab_pdf(context: dict[str, Any]) -> bytes:
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    except Exception as exc:
        raise HTTPException(status_code=500, detail="No fallback PDF engine available") from exc

    def _page_footer(canvas: Any, doc: Any) -> None:
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#64748b"))
        canvas.drawString(doc.leftMargin, 0.42 * inch, "Generated by Friction Finder")
        canvas.drawRightString(letter[0] - doc.rightMargin, 0.42 * inch, f"Page {doc.page}")
        canvas.restoreState()

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=0.45 * inch,
        rightMargin=0.45 * inch,
        topMargin=0.45 * inch,
        bottomMargin=0.65 * inch,
        title="COO Friction Intelligence Report",
    )
    styles = getSampleStyleSheet()
    brand_style = ParagraphStyle("brand_style", parent=styles["BodyText"], fontName="Helvetica-Bold", fontSize=9, leading=11, textColor=colors.HexColor("#99f6e4"))
    title_style = ParagraphStyle("title_style", parent=styles["Heading1"], fontName="Helvetica-Bold", fontSize=22, leading=26, textColor=colors.white)
    subtitle_style = ParagraphStyle("subtitle_style", parent=styles["BodyText"], fontName="Helvetica", fontSize=11, leading=14, textColor=colors.HexColor("#e2e8f0"))
    meta_style = ParagraphStyle("meta_style", parent=styles["BodyText"], fontName="Helvetica", fontSize=9, leading=11, textColor=colors.HexColor("#cbd5e1"))
    heading_style = ParagraphStyle("heading_style", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=15, leading=18, textColor=colors.HexColor("#0f172a"), spaceAfter=8, spaceBefore=8)
    body_style = ParagraphStyle("body_style", parent=styles["BodyText"], fontName="Helvetica", fontSize=9.4, leading=12.8, textColor=colors.HexColor("#1e293b"))
    muted_style = ParagraphStyle("muted_style", parent=styles["BodyText"], fontName="Helvetica", fontSize=8.2, leading=10.8, textColor=colors.HexColor("#64748b"))
    lane_title_style = ParagraphStyle("lane_title_style", parent=styles["BodyText"], fontName="Helvetica-Bold", fontSize=11.5, leading=14, textColor=colors.HexColor("#0f172a"))
    quote_style = ParagraphStyle("quote_style", parent=styles["BodyText"], fontName="Helvetica-Oblique", fontSize=9, leading=12, textColor=colors.HexColor("#1e293b"))

    story: list[Any] = []

    header_rows = [
        [Paragraph("FRICTION FINDER", brand_style)],
        [Paragraph("COO Friction Intelligence Report", title_style)],
        [Paragraph("Operational bottleneck analysis and automation opportunities", subtitle_style)],
        [
            Paragraph(
                f"Generated: {context.get('generated', '-')}<br/>"
                f"Hourly rate: {context.get('currency_symbol', '')}{context.get('hourly_rate', '-')}/hour "
                f"({context.get('currency_code', 'GBP')})",
                meta_style,
            )
        ],
    ]
    header = Table(header_rows, colWidths=[doc.width])
    header.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#0f172a")),
                ("LEFTPADDING", (0, 0), (-1, -1), 14),
                ("RIGHTPADDING", (0, 0), (-1, -1), 14),
                ("TOPPADDING", (0, 0), (-1, 0), 12),
                ("TOPPADDING", (0, 1), (-1, 1), 3),
                ("TOPPADDING", (0, 2), (-1, 2), 5),
                ("TOPPADDING", (0, 3), (-1, 3), 6),
                ("BOTTOMPADDING", (0, 3), (-1, 3), 12),
            ]
        )
    )
    story.append(header)
    story.append(Spacer(1, 10))

    story.append(Paragraph("Executive Summary", heading_style))
    kpi_cells = [
        Paragraph(f"<font size='7' color='#64748b'>TOTAL PAIN POINTS</font><br/><font size='16'><b>{context.get('kpi_total_pain_points', '0')}</b></font>", body_style),
        Paragraph(f"<font size='7' color='#64748b'>TOTAL HOURS LOST / WEEK</font><br/><font size='16'><b>{context.get('kpi_total_hours_week', '0 h')}</b></font>", body_style),
        Paragraph(f"<font size='7' color='#64748b'>ESTIMATED ANNUAL COST</font><br/><font size='16'><b>{context.get('kpi_annual_cost', '-')}</b></font>", body_style),
        Paragraph(f"<font size='7' color='#64748b'>TOP IMPACT AREA</font><br/><font size='16'><b>{context.get('kpi_top_impact_area', 'None')}</b></font>", body_style),
    ]
    kpi_table = Table([kpi_cells], colWidths=[doc.width / 4.0] * 4)
    kpi_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#dbe3ea")),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#dbe3ea")),
                ("TOPPADDING", (0, 0), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(kpi_table)
    story.append(Spacer(1, 10))

    story.append(Paragraph("ROI Snapshot", heading_style))
    roi_rows = [
        ["Weekly Cost Estimate", "Annual Hours Affected", "Annual Cost Estimate"],
        [context.get("roi_weekly_cost", "-"), f"{context.get('roi_annual_hours', '-')} h", context.get("roi_annual_cost", "-")],
    ]
    roi_table = Table(roi_rows, colWidths=[doc.width / 3.0] * 3)
    roi_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#ecfeff")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0f766e")),
                ("TEXTCOLOR", (0, 1), (-1, 1), colors.HexColor("#0f172a")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 8),
                ("FONTSIZE", (0, 1), (-1, 1), 13),
                ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#99f6e4")),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#ccfbf1")),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(roi_table)
    story.append(Spacer(1, 4))
    story.append(Paragraph("Formula used: hours/week x hourly rate x 52. Figures are directional and conservative for planning.", muted_style))
    story.append(Paragraph(f"Sensitivity range: weekly {context.get('roi_weekly_range', '-')} | annual {context.get('roi_annual_range', '-')}.", muted_style))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Top Automation Opportunities", heading_style))
    backlog = list(context.get("ranked_backlog", []))
    if backlog:
        rows: list[list[str]] = [["Rank", "Pain Point", "Team", "Impact", "Priority", "Recommended Approach"]]
        for item in backlog[:10]:
            rows.append(
                [
                    str(item.get("rank", "")),
                    f"{str(item.get('title', '-'))[:40]}\n{str(item.get('category', '-')).replace('_', ' ').title()}",
                    str(item.get("team", "-")),
                    str(item.get("impact_hours_fmt", "-")),
                    str(item.get("priority_score_fmt", "-")),
                    f"{str(item.get('automation_type', '-')).replace('_', ' ').title()}\n{str(item.get('suggested_solution', '-'))[:65]}",
                ]
            )
        backlog_table = Table(rows, colWidths=[0.42 * inch, 2.1 * inch, 0.95 * inch, 0.75 * inch, 0.75 * inch, 2.03 * inch], repeatRows=1)
        backlog_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 8),
                    ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#cbd5e1")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("ALIGN", (0, 1), (0, -1), "CENTER"),
                    ("ALIGN", (3, 1), (4, -1), "RIGHT"),
                    ("FONTSIZE", (0, 1), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        story.append(backlog_table)
    else:
        story.append(Paragraph("No ranked opportunities available.", body_style))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Recommended Automation Roadmap", heading_style))
    quick_items = [f"• {i.get('title', '-')}: {i.get('impact_hours_fmt', '-')} | Priority {i.get('priority_score_fmt', '-')}" for i in context.get("roadmap_quick_wins", [])[:5]]
    medium_items = [f"• {i.get('title', '-')}: {i.get('impact_hours_fmt', '-')} | Priority {i.get('priority_score_fmt', '-')}" for i in context.get("roadmap_medium_impact", [])[:5]]
    strategic_items = [f"• {i.get('title', '-')}: {i.get('impact_hours_fmt', '-')} | Priority {i.get('priority_score_fmt', '-')}" for i in context.get("roadmap_strategic", [])[:5]]
    roadmap_cols = [
        [Paragraph("Quick Wins", lane_title_style), Paragraph("<br/>".join(quick_items) if quick_items else f"• No quick wins above threshold ({context.get('quick_win_threshold', '5.0')} h/week).", body_style)],
        [Paragraph("Medium Impact", lane_title_style), Paragraph("<br/>".join(medium_items) if medium_items else "• No items currently match this lane.", body_style)],
        [Paragraph("Strategic Automation", lane_title_style), Paragraph("<br/>".join(strategic_items) if strategic_items else "• No items currently match this lane.", body_style)],
    ]
    roadmap = Table([roadmap_cols], colWidths=[doc.width / 3.0] * 3)
    roadmap.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e1")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(roadmap)
    story.append(Spacer(1, 12))

    story.append(Paragraph("Team and Category Breakdown", heading_style))
    team_rows = [["Team", "Count"]]
    for row in context.get("team_rows", [])[:8]:
        team_rows.append([str(row.get("team", "-")), str(row.get("total_fmt", "0"))])
    category_rows = [["Category", "Count"]]
    for row in context.get("category_rows", [])[:8]:
        category_rows.append([str(row.get("category", "-")).replace("_", " ").title(), str(row.get("count_fmt", "0"))])
    if len(team_rows) == 1:
        team_rows.append(["No data", "-"])
    if len(category_rows) == 1:
        category_rows.append(["No data", "-"])

    team_table = Table(team_rows, colWidths=[2.2 * inch, 0.65 * inch], repeatRows=1)
    team_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2f7f5")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0f766e")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#cbd5e1")),
                ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                ("ALIGN", (1, 1), (1, -1), "RIGHT"),
            ]
        )
    )
    category_table = Table(category_rows, colWidths=[2.2 * inch, 0.65 * inch], repeatRows=1)
    category_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8efff")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#1d4ed8")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#cbd5e1")),
                ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                ("ALIGN", (1, 1), (1, -1), "RIGHT"),
            ]
        )
    )
    split = Table([[team_table, category_table]], colWidths=[doc.width / 2.0, doc.width / 2.0])
    split.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 0)]))
    story.append(split)
    story.append(Spacer(1, 12))

    story.append(Paragraph("Systems Involved", heading_style))
    systems = list(context.get("systems_map", []))
    if systems:
        story.append(Paragraph(", ".join([str(s.get("system", "-")) for s in systems[:12]]), muted_style))
        systems_rows = [["System", "Mentions"]]
        for system in systems[:12]:
            systems_rows.append([str(system.get("system", "-")), str(system.get("mentions", 0))])
        systems_table = Table(systems_rows, colWidths=[doc.width * 0.72, doc.width * 0.28], repeatRows=1)
        systems_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#cbd5e1")),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                    ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                    ("ALIGN", (1, 1), (1, -1), "RIGHT"),
                ]
            )
        )
        story.append(Spacer(1, 4))
        story.append(systems_table)
    else:
        story.append(Paragraph("No systems identified.", body_style))

    quotes = list(context.get("quotes", []))
    if quotes:
        story.append(PageBreak())
        story.append(Paragraph("Appendix: Anonymised Quotes", heading_style))
        for quote in quotes[:14]:
            quote_block = Table(
                [
                    [Paragraph(str(quote.get("quote", "")), quote_style)],
                    [Paragraph(f"Pain Point #{quote.get('pain_point_id', '-')}, {quote.get('team', '-')}", muted_style)],
                ],
                colWidths=[doc.width],
            )
            quote_block.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                        ("LINEBEFORE", (0, 0), (0, -1), 2, colors.HexColor("#99f6e4")),
                        ("BOX", (0, 0), (-1, -1), 0.3, colors.HexColor("#dbe3ea")),
                        ("TOPPADDING", (0, 0), (-1, -1), 8),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                        ("LEFTPADDING", (0, 0), (-1, -1), 9),
                    ]
                )
            )
            story.append(quote_block)
            story.append(Spacer(1, 6))

    doc.build(story, onFirstPage=_page_footer, onLaterPages=_page_footer)
    pdf = buffer.getvalue()
    buffer.close()
    return pdf


def _safe_float(value: Any) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def _safe_int(value: Any) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def _fmt_number(value: float, digits: int = 2) -> str:
    return f"{value:,.{digits}f}"


def _fmt_hours(value: Any) -> str:
    return f"{_fmt_number(_safe_float(value), 1)} h"


def _fmt_priority(value: Any) -> str:
    return _fmt_number(_safe_float(value), 2)


def _fmt_currency(value: Any, currency: str) -> str:
    symbol = CURRENCY_SYMBOLS.get(currency, currency)
    return f"{symbol}{_fmt_number(_safe_float(value), 0)}"


def _priority_band(priority: float) -> str:
    if priority >= 12:
        return "high"
    if priority >= 6:
        return "medium"
    return "low"


def _build_report_view_model(
    context: dict[str, Any],
    hourly_rate: float,
    currency: Literal["GBP", "USD", "EUR"],
    quick_win_threshold: float,
) -> dict[str, Any]:
    kpis = context.get("kpis", {})
    top_backlog = list(context.get("top_backlog", []))
    team_breakdown = list(context.get("team_breakdown", []))
    category_breakdown = list(context.get("category_breakdown", []))

    total_hours_week = _safe_float(kpis.get("total_hours_per_week", 0.0))
    annual_hours = total_hours_week * 52
    weekly_cost = total_hours_week * hourly_rate
    annual_cost = annual_hours * hourly_rate
    annual_savings = _safe_float(context.get("estimated_hours_saved", 0.0)) * hourly_rate * 52
    weekly_cost_low = weekly_cost * 0.8
    weekly_cost_high = weekly_cost * 1.2
    annual_cost_low = annual_cost * 0.8
    annual_cost_high = annual_cost * 1.2

    top_impact_area = "None"
    top_categories = kpis.get("top_categories", [])
    if top_categories:
        top_impact_area = str(top_categories[0].get("category", "None")).replace("_", " ").title()

    ranked_backlog: list[dict[str, Any]] = []
    for idx, item in enumerate(top_backlog, 1):
        priority = _safe_float(item.get("priority_score", 0.0))
        impact = _safe_float(item.get("impact_hours_per_week", 0.0))
        ranked_backlog.append(
            {
                **item,
                "rank": idx,
                "priority_class": _priority_band(priority),
                "priority_score_fmt": _fmt_priority(priority),
                "impact_hours_fmt": _fmt_hours(impact),
                "effort_score_fmt": str(_safe_int(item.get("effort_score", 0))),
            }
        )

    quick_wins = [item for item in ranked_backlog if _safe_int(item.get("effort_score")) <= 2]
    medium_impact = [item for item in ranked_backlog if _safe_int(item.get("effort_score")) == 3]
    strategic = [item for item in ranked_backlog if _safe_int(item.get("effort_score")) >= 4]

    max_team_total = max((_safe_int(row.get("total", 0)) for row in team_breakdown), default=1)
    team_rows: list[dict[str, Any]] = []
    for row in team_breakdown:
        total = _safe_int(row.get("total", 0))
        width = (total / max_team_total * 100) if max_team_total else 0
        team_rows.append({**row, "total_fmt": str(total), "bar_width_pct": _fmt_number(width, 0)})

    max_category_total = max((_safe_int(row.get("count", 0)) for row in category_breakdown), default=1)
    category_rows: list[dict[str, Any]] = []
    for row in category_breakdown:
        count = _safe_int(row.get("count", 0))
        width = (count / max_category_total * 100) if max_category_total else 0
        category_rows.append({**row, "count_fmt": str(count), "bar_width_pct": _fmt_number(width, 0)})

    css_text = ""
    if REPORT_CSS_PATH.exists():
        css_text = REPORT_CSS_PATH.read_text(encoding="utf-8")

    return {
        **context,
        "report_css": css_text,
        "hourly_rate": _fmt_number(hourly_rate, 0),
        "currency_code": currency,
        "currency_symbol": CURRENCY_SYMBOLS.get(currency, currency),
        "quick_win_threshold": _fmt_number(quick_win_threshold, 1),
        "kpi_total_pain_points": str(_safe_int(kpis.get("total_pain_points", 0))),
        "kpi_total_hours_week": _fmt_hours(total_hours_week),
        "kpi_annual_cost": _fmt_currency(annual_cost, currency),
        "kpi_annual_savings": _fmt_currency(annual_savings, currency),
        "kpi_top_impact_area": top_impact_area,
        "roi_weekly_cost": _fmt_currency(weekly_cost, currency),
        "roi_annual_hours": _fmt_number(annual_hours, 1),
        "roi_annual_cost": _fmt_currency(annual_cost, currency),
        "roi_weekly_range": f"{_fmt_currency(weekly_cost_low, currency)} to {_fmt_currency(weekly_cost_high, currency)}",
        "roi_annual_range": f"{_fmt_currency(annual_cost_low, currency)} to {_fmt_currency(annual_cost_high, currency)}",
        "ranked_backlog": ranked_backlog[:10],
        "team_rows": team_rows[:12],
        "category_rows": category_rows[:12],
        "roadmap_quick_wins": quick_wins[:5],
        "roadmap_medium_impact": medium_impact[:5],
        "roadmap_strategic": strategic[:5],
    }


@router.get("/report/latest", response_model=ReportRunResponse, dependencies=[Depends(require_app_password)])
def get_latest_report(session_id: str | None = None, session: Session = Depends(get_session)) -> ReportRunResponse:
    query = select(ReportRun)
    if session_id:
        query = query.where(ReportRun.session_id == session_id)
    query = query.order_by(ReportRun.created_at.desc())

    report_run = session.scalar(query)
    if not report_run:
        raise HTTPException(status_code=404, detail="No report found")

    return ReportRunResponse(
        id=report_run.id,
        created_at=report_run.created_at,
        source=report_run.source,
        interview_id=report_run.interview_id,
        session_id=report_run.session_id,
        pdf_path_or_url=report_run.pdf_path_or_url,
        summary=report_run.summary,
        recommendations_json=report_run.recommendations_json,
    )


@router.post("/report/attach", response_model=ReportRunResponse)
def attach_report(
    request: AttachReportRequest,
    session: Session = Depends(get_session),
    _: None = Depends(lambda: require_webhook_secret(get_settings().n8n_webhook_secret)),
) -> ReportRunResponse:
    recommendations_str = None
    if request.recommendations_json:
        recommendations_str = json.dumps(request.recommendations_json)

    report_run = ReportRun(
        source=request.source,
        interview_id=request.interview_id,
        session_id=request.session_id,
        pdf_path_or_url=request.pdf_path_or_url,
        summary=request.summary,
        recommendations_json=recommendations_str,
    )
    session.add(report_run)
    session.commit()
    session.refresh(report_run)

    return ReportRunResponse(
        id=report_run.id,
        created_at=report_run.created_at,
        source=report_run.source,
        interview_id=report_run.interview_id,
        session_id=report_run.session_id,
        pdf_path_or_url=report_run.pdf_path_or_url,
        summary=report_run.summary,
        recommendations_json=report_run.recommendations_json,
    )
